import pytest
import logging
from fastapi.testclient import TestClient
from uuid import uuid4
from datetime import datetime

from db_connection import session_scope
from main import app, Task

client = TestClient(app)

random_task_id = str(uuid4())
session_scope = pytest.fixture(session_scope, scope="module")


def test_get_tasks():
    response = client.get("/tasks")
    logging.info(response.json())

    assert response.status_code == 200


def test_add_task():
    task_test = Task(
        id=random_task_id,
        title="generated by test module test_main.py",
        content="test content",
        deadline=datetime.now(),
    )
    logging.info(task_test)

    response = client.post("/tasks", data=task_test.json())
    logging.info(response.json())

    assert response.status_code == 200


def test_delete_task():
    response = client.delete(f"/tasks/{random_task_id}")

    assert response.status_code == 204
